2019-12-30 15:29:17,363 ERROR: Exception on /BoroughSplitter [POST] [inC:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 43, in split_by_borough
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 43, in <lambda>
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
TypeError: 'float' object is not subscriptable
2019-12-30 15:30:01,649 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:32:13,485 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:34:04,573 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:34:31,969 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:34:36,877 ERROR: Exception on /BoroughSplitter [POST] [inC:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 42, in split_by_borough
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 42, in <lambda>
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
TypeError: 'float' object is not subscriptable
2020-01-02 10:41:08,568 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 11:30:44,074 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 11:47:45,913 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 11:50:07,397 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 11:50:50,541 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:07:50,548 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:09:28,237 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:10:16,793 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:11:06,401 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:13:06,268 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:13:49,550 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:14:40,448 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:14:46,472 ERROR: Exception on /BrownsvilleTRCclean [POST] [inC:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BrownsvilleTRCclean.py", line 408, in upload_BrownsvilleTRCclean
    'format': problem_format})
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\xlsxwriter\worksheet.py", line 100, in cell_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\xlsxwriter\worksheet.py", line 2256, in conditional_format
    if options['criteria'] == 'containsText':
KeyError: 'criteria'
2020-01-02 12:16:06,132 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:18:01,489 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:19:52,540 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:21:17,620 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:23:09,168 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-02 12:31:28,128 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 12:27:53,983 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 13:40:54,098 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
